export const EMOTION_MOOD_MAPPING = {
  'admiration': 'Focused & Inspired',
  'amusement': 'Light & Energetic',
  'anger': 'Intense & Motivated',
  'annoyance': 'Frustrated & Alert',
  'approval': 'Positive & Engaged',
  'caring': 'Thoughtful & Warm',
  'confusion': 'Curious & Searching',
  'curiosity': 'Eager to Learn',
  'desire': 'Motivated & Ambitious',
  'disappointment': 'Reflective & Pensive',
  'disapproval': 'Critical & Evaluative',
  'disgust': 'Cautious & Selective',
  'embarrassment': 'Self-Aware & Considerate',
  'excitement': 'Hyper-Engaged & Energized',
  'fear': 'Alert & Defensive',
  'gratitude': 'Appreciative & Content',
  'grief': 'Emotional & Introspective',
  'joy': 'Happy & Optimistic',
  'love': 'Passionate & Warm',
  'nervousness': 'Anxious & Alert',
  'optimism': 'Hopeful & Driven',
  'pride': 'Confident & Satisfied',
  'realization': 'Enlightened & Clear',
  'relief': 'Relaxed & Relieved',
  'remorse': 'Contemplative & Regretful',
  'sadness': 'Melancholic & Reflective',
  'surprise': 'Alert & Curious',
  'neutral': 'Balanced & Calm',
};

